//! Inherited inventory budgets and unchanged v4 DTO edges for this isolated v5 candidate.

pub(super) use zryna_syntax::v4::{
    MAX_AGGREGATE_OPERANDS_PER_PROJECT, MAX_BLOCKS_PER_FUNCTION, MAX_BLOCKS_PER_PROJECT,
    MAX_DATA_DECLARATIONS_PER_MODULE, MAX_DATA_DECLARATIONS_PER_PROJECT,
    MAX_ELEMENTS_PER_CONSTRUCTION, MAX_EXPRESSIONS_PER_FUNCTION, MAX_EXPRESSIONS_PER_PROJECT,
    MAX_FIXED_ARRAY_LENGTH, MAX_FUNCTIONS_PER_MODULE, MAX_FUNCTIONS_PER_PROJECT,
    MAX_IMPORTED_NAMES_PER_DECLARATION, MAX_IMPORTED_NAMES_PER_PROJECT, MAX_IMPORTS_PER_MODULE,
    MAX_IMPORTS_PER_PROJECT, MAX_INITIALIZERS_PER_CONSTRUCTION, MAX_MATCH_ARMS_PER_EXPRESSION,
    MAX_MATCH_ARMS_PER_PROJECT, MAX_MEMBERS_PER_DECLARATION, MAX_MEMBERS_PER_PROJECT,
    MAX_NESTING_DEPTH, MAX_PARAMETERS_PER_FUNCTION, MAX_PARAMETERS_PER_PROJECT,
    MAX_STATEMENTS_PER_FUNCTION, MAX_STATEMENTS_PER_PROJECT, MAX_TYPE_NODES_PER_MODULE,
    MAX_TYPE_NODES_PER_PROJECT, RawBlockSyntax, RawDataField, RawElseSyntax, RawEnumVariant,
    RawFieldInitializer, RawFieldInitializerKind, RawIdentifierSyntax, RawImportBindingSyntax,
    RawImportSyntax, RawMatchArm, RawModuleSpecifierSyntax, RawStatementKind, RawStatementSyntax,
};
pub(super) use zryna_syntax::v5::*;
